name: zego_uikit_prebuilt_live_audio_room
description: PrebuiltLiveAudioRoom is a Live Audio Room kit that provides a ready-made group voice chat that supports up to 8 hosts and co-hosts to connect with millions of users downstage.
version: 1.0.0
homepage: https://www.zegocloud.com/
repository: https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_live_audio_room

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_screenutil: ^5.5.3+2
  flutter_styled_toast: ^2.1.3
  zego_uikit: ^1.7.0
  zego_uikit_signaling_plugin: ^1.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  import_sorter: ^4.6.0  # run 'flutter pub run import_sorter:main'

flutter:
  assets:
    - assets/icons/